### ISSUE TITLE
Question: hash and integrity management

### ISSUE THREAD

**Issue by antoninoLorenzo** [laktak/chkbit#13]
Hi, 
I got here while learning about file integrity, as my understanding of the code the hash of a file is kept in a dictionary in the `Index` class, so I assume that chkbit cannot guarantee that the file wasn't modified while it wasn't running as it hasn't a persistent hash history; also, it isn't clear to me if there is an alerting mechanism while it is running or you must manually check.

About the first point, I was wondering if a *SQLite* database wouldn't be a better fit, it would have the advantages of using files and would make it possible to have a persistent history; still, it would also introduce more complexities, such as database management but, more important, the hashes should be encrypted -> the key should be kept somewhere safe.

I would like to know more about the project, given my recent interest in file integrity.

**Comment by laktak** [comment]
This is explained in the README, see [USAGE](https://github.com/laktak/chkbit-py?tab=readme-ov-file#usage). 

chkbit uses one index file per directory to track hashes.

**Comment by antoninoLorenzo** [comment]
Yes, I tried it out and I noticed the following:

The hashes are kept inside `.chkbit`, this solves my question about how are updates managed, however storing the hashes in the file is a vulnerability:
```
{
	"v":2,
	"idx": {
	"file_to_watch.txt":{
		"mod":1709627283794,
		"a":"blake3",
		"h":"3fba5250be9ac259c56e7250c526bc83bacb4be825f2799d3d59e5b4878dd74e"
	},
	...
	"idx_hash":"c490ca9fd73829664a0ced0135420858"
}
```

As an attacker I would modify the files, compute the hash, and manually update them inside `.chkbit`; when the file owner runs `chkbit PATH` the hashes are loaded from the modified file; I think you should encrypt the hashes (a symmetric algorithm would be a good fit) and figure out a way to store the private key.

If you think I am missing out on something I would like to be corrected.

**Comment by laktak** [comment]
Not sure about your usecase. chkbit's job is to detect errors (e.g. flipped bits) or changes (e.g.  compression applied to an image/video by a cloud provider). It's not there to protect against an attacker, that would be the job of disk encryption.

**Comment by antoninoLorenzo** [comment]
Ok, I think that I misunderstood its objective, I thought of it more as a security tool.
However, the use case I had in mind was log tampering protection.

**Comment by y653** [comment]
Reading the above, the following question comes in my mind: What about if a .chkbit file suffers bitrot and some bytes in there are flipped? I think that this would create some problems, since the checksuming would fail, even if the original files are intact. In another similar program, that uses on db file to store checksums, this db file is checksumed in a different file, and the program first check the db integrity and then continues. I do not know if something like that would be feasible in chkbit, since it would double the number of .chkbit files.

An usefull adition for me, would be to give an option to store all checksums in one file, at the root of the folder tested for bitrot. It could be one .chkbit file but for all directories and subdirectories. This way, it could be checksummed as well, to verify its integrity. There could be a flag for the user to indicate if he/she prefers the current, one file per directory, structure, or a new one, one file for the whole structure.

What do you think about it? Could that be implemented as well?

Congratulations for your great work!!

**Comment by laktak** [comment]
`.chkbit` files are protected by their own hash. There are no plans to make a central database for the indices.

**Comment by y653** [comment]
This is very good news. I think that you should mention this in the read.me file. It is an important safeguarding measure.

Where is this hash stored? Inside the .chkbt file? Is it the "idx_hash"?

I tried the following: I opened the .chkbit file and I changed one of the files' hash value, and saved it back. I run again chkbit and the output is:
```
EIX .chkbit
ok  ...
...
ok  ...
DMG Linux distros comparison.ods
ok ...
...
chkbit detected damage in these files:
Linux distros comparison.ods
error: detected 1 file with damage!
```
The first line indication is that the .chkbit file has changed? What EIX stands for? I guess DMG means damaged, and indeed this is the file whose checksum I changed.
